# Puppet Forge Address
  forge "http://forge.puppetlabs.com"

  # Modules from the Puppet Forge
  mod "crayfishx/firewalld"
  mod "cvquesty/puppetdev"
  mod "nanliu/staging"
  mod "puppetlabs/accounts"
  mod "puppetlabs/apache"
  mod "puppetlabs/concat"
  mod "puppetlabs/firewall"
  mod "puppetlabs/inifile"
  mod "puppetlabs/inventory"
  mod "puppetlabs/limits"
  mod "puppetlabs/motd"
  mod "puppetlabs/ntp"
  mod "puppetlabs/ruby"
  mod "puppetlabs/stdlib"
  mod "puppetlabs/vcsrepo"
  mod "saz/resolv_conf"
  mod "saz/rsyslog"
  mod "saz/ssh"
  mod "saz/sudo"
  mod "stahnma/epel"
  mod "zack/r10k"
